import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;    //This is typescript defining what kind of data will children accept.
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h2>Nav Items</h2>
        {children}
      </body>
    </html>
  );
}
